### ISSUE TITLE
Outputvariable for Sarif-Report "interesting" prefix

### ISSUE THREAD

**Issue by Bjego** [aquasecurity/trivy-azure-pipelines-task#113]
**Describe the bug**
When I enable the extra sarif report, then the output variable ist set like this
```
__SYSTEM_POST_1_SARIFREPORT=/mnt/vss/_work/_temp/trivy-results-0.2574772316879166.sarif.json
```

I am expecting the name: sarifReport for the output, or maybe trivy_sarifReport

Steps to reproduce:
```yaml
      - task: trivy@1
        name: trivy
        displayName: Trivy CVE Scan
        inputs:
          version: "latest"
          docker: false
          path: "."
          severities: "CRITICAL,HIGH,MEDIUM,LOW"
          exitCode: "0"
          scanners: "vuln,license"
          sarifOutput: true

      - task: CmdLine@2
        displayName: "Printenv"
        inputs:
          script: |
            printenv
```

**Trivy Azure Pipeline Task Verison**
1.7.0 (Latest)

**Hosted or Self-hosted Agent**
Hosted

**Trivy as Docker?**
No

**Error message**
Variable prefix seems to be incorrect.

**Comment by owenrumney** [comment]
Hey @Bjego - my understanding is that the `__SYSTEM_POST_1_` prefix is used internally but that you can still access the output using the dependencies in the following step

```
dependencies.JobA.outputs['trivy.sarifOutput'] 
```
or whatever your trivy step is called

**Comment by Bjego** [comment]
Thank you - I knew there was something - but I didn't find the documentation today.
Ages ago I saw this kind of using taskoutput in the docs.
Can be closed!

**Comment by Bjego** [comment]
I've checked the code.. 
It looks like the task.setvariable has an overload to define the variable as Task output:
```js
        // variable is not a secret, but an output variable
        task.setVariable(outputKey, localOutput, false, true);
```

As this still doesn't work:

![Image](https://github.com/user-attachments/assets/def3060c-9f78-43bf-975a-28b38808aac6)

But according to the docs it should:

See the (shortend= example: 
```yaml
jobs:
- job: A
  steps:
 ..
  - bash: |
     echo "##vso[task.setvariable variable=myOutputJobVar;isOutput=true]this is the same job too"
    name: setOutput
  ..
  - bash: |
     echo $(setOutput.myOutputJobVar)
```

https://learn.microsoft.com/en-us/azure/devops/pipelines/process/set-variables-scripts?view=azure-devops&tabs=bash#set-an-output-variable-for-use-in-the-same-job

**Comment by owenrumney** [comment]
Hey @Bjego - great spot, thanks - I've just fixed it in the PR that's active now

Pipeline excerpt

```
- task: trivy@1
  name: trivy_nginx
  displayName: 'Scan nginx for vulnerabilities and license issues'
  inputs:
    version: 'latest'
    exitCode: '0'
    image: 'nginx'
    scanners: 'vuln,license'
    severities: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
    ignoreUnfixed: true
    jsonOutput: true
    sarifOutput: true
- task: CmdLine@2
  inputs:
    script: 'echo $(trivy_nginx.jsonReport)'
```

Output

```
Starting: CmdLine
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.250.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents:
echo /home/owen/azure-agent/_work/_temp/trivy-results-0.44026364206646984.json
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /home/owen/azure-agent/_work/_temp/f25188f4-6c2b-4726-8134-333335d84d60.sh
/home/owen/azure-agent/_work/_temp/trivy-results-0.44026364206646984.json

Finishing: CmdLine

```
