### ISSUE TITLE
Vulnerabilities display issue when scanned multiple images

### ISSUE THREAD

**Issue by nosalan** [aquasecurity/trivy-azure-pipelines-task#13]
I invoke Trivy task twice in the pipeline and while the report contains tabs of both scans, when switching between the tabs the list of vulnerabilities in not refreshed. 
On the screenshot below, there are two scan results, one with 12 vulnerabilities and the other one with 0 vulnerabilities. When I switch to the second tab, it still shows vulnerabilities list from the first tab.

![image](https://user-images.githubusercontent.com/2273250/195326599-837cc8d4-086d-4e29-a684-1dea41d12698.png)

Here are the tasks:

```
- task: Docker@2
  displayName: Login to Container Registry
  inputs:
    containerRegistry: "testmanagement"
    command: "login"
- task: trivy@1
  displayName: Scanning XXXXXX-client:$(DOCKER_TAG)
  inputs:
    image: XXXXXX/XXXXXX-client:$(DOCKER_TAG)
    docker: false
    exitCode: 0
- task: trivy@1
  displayName: Scanning XXXXXX-flows:$(DOCKER_TAG)
  inputs:
    image: XXXXXX/XXXXXX-flows:$(DOCKER_TAG)
    docker: false
    exitCode: 0
```
