### ISSUE TITLE
Feature request: control which severity levels are used

### ISSUE THREAD

**Issue by AndrewGretton** [aquasecurity/trivy-azure-pipelines-task#14]
We currently use a home-grown trivy setup, and we fail the build if any `critical` or `high` issues are found (by setting the exit code to be > 0). We'd love to move to this task instead, but right now it seems we can only fail the build if _any_ issues are found, which isn't quite what we need.

Can I suggest that there's an additional input surfaced for the `severity` argument please? Example:

```
jobs:
- job: Scan the local project
  steps:
  - task: trivy@1
    inputs:
      path: .
      severity: CRITICAL,HIGH
```
