### ISSUE TITLE
[Feature]Add Support for K8S scanning

### ISSUE THREAD

**Issue by Bjego** [aquasecurity/trivy-azure-pipelines-task#141]
**Describe the feature**
Trivy is able to scan kubernetes clusters and namespaces for CVEs.
Please extend the plugin so that I can scan given namespaces in my k8s for CVEs.
The CVEs should appear in the pipeline summary.

https://trivy.dev/dev/docs/target/kubernetes/#:~:text=Trivy%20can%20connect%20to%20your%20Kubernetes%20cluster%20and,as%20a%20Kubernetes%20Operator%2C%20and%20continuously%20scan%20it.

**Acceptance criteria**
- The plugin has a new dropdown entry to scan k8s clusters
- The plugin has a new inputfield to enter comma delimited a list of namespaces
- The plugin performs only CVE checks in the beginning
- The results are listed in the "Trivy" report at the end of the pipeline
- It is okay, that the pipeline requires a k8s login task before running trivy

**Example pipeline**
```yaml
- task: Kubernetes@1
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: 'someK8s'
      namespace: 'someNamesapce'
      command: 'login'
- task: trivy@1
    inputs:
      docker: false
      version: 'latest'
      type: 'k8s'
      namespace: 'someNamesapce'
```

**Comment by bonddim** [comment]
In my mind, this feature should be implemented in V2.
V1 is already overloaded with inputs, which should be combined as selectors.

**Comment by owenrumney** [comment]
This would be a new task entirely - the plugin for trivy that works against k8s has a different enough output to and reduced user base to warrant not adding it into this task

**Comment by owenrumney** [comment]
> In my mind, this feature should be implemented in V2. V1 is already overloaded with inputs, which should be combined as selectors.

@bonddim - by selector do you mean grouping logical input values together into different execution "modes" or something different? I'm not completely clear

**Comment by bonddim** [comment]
I meant grouping not on Azure UI, but something like:

```yaml
inputs:
 runMethod:  docker | install | pre-installed <- installation or run method 
 targetType: fs | image | repo | k8s <- any supported
 target: path | imageName ... <- just an empty required string 
 additionalReports: sarif, spdx .... <- convert multiple boolean inputs to delimited string
 ...
```

And such breaking change should be in Trivy@2.
