### ISSUE TITLE
Using Trivy CLI with the Plugin for Reporting

### ISSUE THREAD

**Issue by C1ph3R-s** [aquasecurity/trivy-azure-pipelines-task#146]
#### Describe 

Hello,

I have a question regarding the plugin. I would like to use this plugin solely for reporting while running Trivy via the CLI.

Do you have any configuration that allows this? How can I publish the report in a format that the plugin can parse?

Thank you in advance for your help!

**Comment by owenrumney** [comment]
@C1ph3R-s  - you can run using the CLI instead of docker by setting `docker: false` in the task.

Something like this;


```yaml
- job: use_binary
  steps:
  - task: trivy-dev@1
    displayName: 'Trivy Scan'
    inputs:
      docker: false
      version: 'latest'
      cosignOutput: true
      sarifOutput: true
      spdxOutput: true
      spdxjsonOutput: true
      options: '--scanners vuln,misconfig --db-repository ghcr.io/aquasecurity/trivy-db:2,aquasec/trivy-db:2'
```

There are inputs for additional reports which would then be downloadable through the Trivy tab in the UI.

![Image](https://github.com/user-attachments/assets/7f138730-0f9e-42ae-aeb6-3d9480d16f67)
