### ISSUE TITLE
How i can scan a private GitHub repo using azure DevOps pipeline

### ISSUE THREAD

**Issue by owenrumney** [aquasecurity/trivy-azure-pipelines-task#153]
### Discussed in https://github.com/aquasecurity/trivy-azure-pipelines-task/discussions/152

<div type='discussions-op-text'>

<sup>Originally posted by **MoZiZ00** March 28, 2025</sup>
### Question

How i can scan a terraform files in private GitHub repo using azure DevOps pipeline 
this is mu current code:

`trigger: none

pool:
  vmImage: windows-latest

stages:
  - stage: 'PS'
    jobs:
      - job: 'Analyze'
        steps:
          - script: |
              dir $(Build.SourcesDirectory)\TrivyPOC\Terraform
            displayName: 'List files in TrivyPOC/Terraform'
          - task: trivy@1
            inputs:
              docker: false
              useSystemInstallation: false
              exitCode: '0'
              type: 'filesystem'
              scanners: 'vuln,misconfig,secret,license'
              severities: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
              path: '$(Build.SourcesDirectory)\TrivyPOC\Terraform'
              tableOutput: true
            continueOnError: true
            `

### Target

Git Repository

### Scanner

Misconfiguration

### Output Format

Table

### Mode

None

### Operating System

windows

### Version

```bash
Version      : 2.250.1
```
</div>

**Comment by MoZiZ00** [comment]
Hi @owenrumney 
sorry of the inconvenience 

would you please to share when you will be able to share the fix as we are planning to test it in prod next week

also is there an alternative ways like use GitHub pipeline instead of azure pipeline till we have the fix

**Comment by owenrumney** [comment]
> Hi @owenrumney 
> sorry of the inconvenience 
> 
> would you please to share when you will be able to share the fix as we are planning to test it in prod next week
> 
> also is there an alternative ways like use GitHub pipeline instead of azure pipeline till we have the fix 

I've actually done the coding but I've been at Kubecon this week so need to release it. It'll be there by Monday if not sooner

**Comment by owenrumney** [comment]
Hey @MoZiZ00  - I've updated v1 of the trivy task to support repos, set the `type` to `repo` and the `path` to the url of the repo

If its private you need to create a variable and then set that in the env

![Image](https://github.com/user-attachments/assets/17a70e7f-7e2f-453e-91cc-61342950754a)

![Image](https://github.com/user-attachments/assets/3e1c2163-9eb1-4d14-9fb2-8dfbbd5f8089)

```
jobs:
- job: scan_remote_project
  displayName: "Scan remote repo"
  steps:
  - task: trivy-dev@1
    inputs:
      docker: false
      version: 'latest'
      type: 'repo'
      path: 'https://github.com/owenrumney/trivy-bad'
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)
```

a much improved v2 has been contributed which I'll make more generally available this week once docs are updated etc, but this should get you moving for scanning remote repos for now.

Shout if issues and I'll look asap

Note, the Trivy task version is 1.13.78 of the 1.13.0 pipeline release. It should auto update but I've noticed sometimes I need my pipeline to run twice to pickup the latest task *might just be me

**Comment by owenrumney** [comment]
Hey @MoZiZ00  - when you scan using repo, it just clones it to a temp location and scans it with a filesystem scan. If you're looking to scan a specific path within a remote repo, you're going to have to clone the repo then scan the path, something like

```
jobs:
- job: clone_then_scan
  steps:
  - script: |
        git clone https://github.com/MicrosoftCSUDevAdvUK/real_deal.git
    displayName: 'Clone to temp dir'
    workingDirectory: $(Agent.TempDirectory)
  - task: trivy-dev@1
    inputs:
      docker: false
      path: $(Agent.TempDirectory)/real_deal/assets/css
      exitCode: 0
      scanners: 'vuln,misconfig,secret,license'
```

**Comment by owenrumney** [comment]
If your script needs a github token to access a private repo, you'd do something like

```
- script: |
    git clone https://username:$(GIT_PAT)@github.com/myorg/private-repo.git
  displayName: 'Clone to temp dir'
  workingDirectory: $(Agent.TempDirectory)
  env:
    GIT_PAT: $(GIT_PAT)
```

Then add a variable to the pipeline called `GIT_PAT` with the required scope and permissions

**Comment by MoZiZ00** [comment]
Hi @owenrumney 
Thanks a lot for your reply,

yes, it is working fine with public repo 

but actually, i want to use it with private repo and i have tried what you mentioned for the private repo and i have the same issue that that results are empty i am not sure if i am doing something wrong please check the below:


this is my code:

        steps:
          - script: |
                 git clone  git clone https://username:$(GIT_PAT)@github.com/myorg/private-repo.git
            displayName: 'Clone to temp dir'
            workingDirectory: $(Agent.TempDirectory)



          - task: trivy@1
            inputs:
              docker: false
              useSystemInstallation: false
              exitCode: '0'
              version: 'latest'
              type: 'repo'
              scanners: 'vuln,misconfig,secret,license'
              severities: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
              path: $(Agent.TempDirectory)/private-repo
            env:
              GITHUB_TOKEN: $(GITHUB_TOKEN)
              GIT_PAT: $(GIT_PAT)
              tableOutput: true
            continueOnError: true

**Comment by owenrumney** [comment]
Hey @MoZiZ00 - I think it's just that you're not passing the pat token to the env of the script

**Comment by owenrumney** [comment]
It looks to me from that path that it isn't actually scanning `/mnt/vss/_work/_temp/<private_repo>` but in fact the temp file.

I also note in your code above you have 

```
git clone git clone <url>
```

is that just a typo in this issue or is that what you have in the script?

When you check the logs for the job, does it successfully clone the report into the temp dir?

**Comment by MoZiZ00** [comment]
yes it was typo in copy past

this is the logs for clone task it seems it is not cloning it to temp path

<img width="516" alt="Image" src="https://github.com/user-attachments/assets/faafa4ec-cfae-4144-b32b-da6fcb60b49f" />

**Comment by owenrumney** [comment]
@MoZiZ00 - I've just tried it with the following

```
  steps:
  - script: |
        git clone https://x-access-token:$(GITHUB_TOKEN)@github.com/owenrumney/trivy-bad.git
    displayName: 'Clone to temp dir'
    workingDirectory: $(Agent.TempDirectory)
    
  - task: trivy@1
    inputs:
      docker: false
      path: $(Agent.TempDirectory)/trivy-bad
      exitCode: 0
      scanners: 'vuln,misconfig,secret,license'
```

Where `trivy-bad` is a private repo and $(GITHUB_TOKEN) is a pipeline variable. 

It looks like your repo is being cloned correctly, but I still thing your trivy inputs are incorrect, especially if it says `Repository: /mnt/vss....` and not `FileSystem: /mnt/vss....`

![Image](https://github.com/user-attachments/assets/519623f3-f55d-4d39-893a-1b5d32f5c05d)

Can you double check that your inputs don't have `type: repo` and that the path is `$(Agent.TempDirectory)/mcs-azure-security-platform`
