### ISSUE TITLE
Add scanning for SBOM's

### ISSUE THREAD

**Issue by Ozaiy** [aquasecurity/trivy-azure-pipelines-task#164]
#### Describe the bug

Question: When will the Trivy@1 and Trivy@2 task be able to scan SBOM's?

**Comment by Ozaiy** [comment]
Hi @owenrumney Yes thats exactly it i want to run trivy sbom <pathToSBOMfile> that takes in  CycloneDX, SPDX, SPDX JSON type files.

**Comment by owenrumney** [comment]
Okay @Ozaiy - updated so you can run with the sbom using `type: sbom` using the @v2 version

```
- job: scan_image
  steps:
  - task: trivy@2
    name: scanImage
    inputs:
      version: 'latest'
      type: 'image'
      target: 'nginx'
      reports: 'cyclonedx'
    continueOnError: true

  - task: trivy@2
    displayName:  "Process SBOM"
    inputs:
      version: 'latest'
      type: 'sbom'
      target: '$(scanImage.cyclonedxReport)'
      ignoreScanErrors: true
```
