### ISSUE TITLE
Cyclonedx report has xml extension but probably should json as the file content is json.

### ISSUE THREAD

**Issue by MMarus** [aquasecurity/trivy-azure-pipelines-task#166]
#### Describe the bug
When using the "cyclonedxReport" format the file extension is `.xml` however the content inside is a json format.
Would it be possible to change the extension name to `json`?
Also it's necessary to provide `--list-all-pkgs` in order to get a proper SBOM report otherwise the file does not list any dependencies in case there are no vulnerabilities.

#### Agent details

* Type: Microsoft-Hosted Agent
* OS: Linux
* Version: Image: ubuntu-24.04 - Version: 20250413.1.0

#### Task Version

Tried with version 1 and also version 2. (v1.15.0).

#### Task Inputs

```yaml
- task: trivy@1
  displayName: Trivy - code scan
  inputs:
    path: .
    severities: CRITICAL,HIGH
    jsonOutput: true
    tableOutput: true
    cyclonedxOutput: true
    type: 'repo'
    options: '--list-all-pkgs'

  - task: trivy@2
    inputs:
      version: 'latest'
      debug: true
      type: 'repo'
      reports: 'github, table, html, junit, cyclonedx'
      publish: true
      options: '--list-all-pkgs'
      path: .
      severities: CRITICAL,HIGH

```
