### ISSUE TITLE
trivy@2 Unexpected token Agent.TempDirectory

### ISSUE THREAD

**Issue by joaquin386** [aquasecurity/trivy-azure-pipelines-task#169]
#### Describe the bug

SyntaxError: Unexpected token ?

#### Agent details

* Type: Self-Hosted Agent
* OS: Linux X64
* Version: 3.218.0
```
Starting: Initialize job
Agent name: 'ado-agent-scaledjob-ukdxl-java-gf4jj-7hl4q'
Agent machine name: 'ado-agent-scaledjob-ukdxl-java-gf4jj-7hl4q'
Current agent version: '3.218.0'
Agent running as: 'root'
Prepare build directory.
Set build variables.
Download all required tasks.
Downloading task: NodeTool (0.247.1)
Downloading task: UseNode (1.248.1)
Downloading task: Bash (3.250.1)
Downloading task: Cache (2.198.0)
Downloading task: trivy (2.2.83)
Downloading task: PublishTestResults (2.254.0)
Checking job knob settings.
   Knob: DockerActionRetries = true Source: $(VSTSAGENT_DOCKER_ACTION_RETRIES) 
   Knob: AgentToolsDirectory = /azp/tools Source: ${AGENT_TOOLSDIRECTORY} 
   Knob: ContinueAfterCancelProcessTreeKillAttempt = true Source: $(VSTSAGENT_CONTINUE_AFTER_CANCEL_PROCESSTREEKILL_ATTEMPT) 
Finished checking job knob settings.
Start tracking orphan processes.
```

#### Task Version

Azure Extention: 1.16.1

#### Task Inputs

```yaml
              - task: trivy@2
                name: TrivyCurrent
                displayName: "Trivy Filesystem and Misconfiguration Scan"
                inputs:
                  version: $(Profile.TrivyVersion)
                  type: 'filesystem'
                  target: '.'
                  scanners: 'misconfig,vuln,license,secret'
                  severities: 'HIGH,CRITICAL'
                  ignoreScanErrors: true
                  reports: 'github, html, junit'
                  publish: true
```

#### Error message

```log
Starting: Trivy Filesystem and Misconfiguration Scan
==============================================================================
Task         : Trivy
Description  : Trivy is the world's most popular open source vulnerability and misconfiguration scanner. It is reliable, fast, extremely easy to use, and it works wherever you need it.
Version      : 2.2.83
Author       : Aqua Security
Help         : https://github.com/aquasecurity/trivy-azure-pipelines-task/docs/trivyv2.md
==============================================================================
##[error]Unhandled: Unexpected token ?
##[error]/azp/_work/_tasks/trivy_8f9cb13f-f551-439c-83e4-fac6801c3fab/2.2.83/dist/runner.js:13
const agentTmp = task.getVariable('Agent.TempDirectory') ?? os_1.default.tmpdir();
                                                          ^

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/azp/_work/_tasks/trivy_8f9cb13f-f551-439c-83e4-fac6801c3fab/2.2.83/dist/index.js:9:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

When running:
```
              - bash: |
                  env
                displayName: "Environment Variables"
```
Return is:
```
AGENT_TEMPDIRECTORY=/azp/_work/_temp
```

**Comment by owenrumney** [comment]
can you confirm the node version you're running on the agent please. This kind of looks like a node version, but I want to rule it out

**Comment by bonddim** [comment]
What node version do you have on your agent?

**Comment by owenrumney** [comment]
Looks like you're on an agent that is about 2yrs old, so I'm guessing the node version is the issue. Are you able to upgrade node and it might be worth looking at bringing the agent up to date? current is [4.255.0](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v4.255.0)

**Comment by joaquin386** [comment]
Node version 18. I can not really update to that higher version without some regression test to make sure all the agents workj with all the pipelines.

**Comment by owenrumney** [comment]
What about if you used

```
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js 20.x'
```

I'm trying to find a confirmation, but it looks like the agent you're using only supports up to node 16
