### ISSUE TITLE
Target input required parameter missing in the documentation

### ISSUE THREAD

**Issue by julienLemarie** [aquasecurity/trivy-azure-pipelines-task#179]
Hello,

In the documentation, the example concerning the scan of a Docker image:

```
  - task: trivy@2
    inputs:
      type: 'image'
      image: my.private.registry/org/my-image:latest
```

but there is an error:

```
Starting Trivy task...
##[error]Input required: target
Finishing: Trivy scan on Docker image
```
