### ISSUE TITLE
🔧 Feature Request: Allow controlling task outcome based on severity threshold

### ISSUE THREAD

**Issue by k0muc** [aquasecurity/trivy-azure-pipelines-task#182]
#### Describe the bug

Currently, the `trivy@2` task does not provide a way to control the final task status (`Succeeded`, `SucceededWithIssues`, or `Failed`) based on the severity of vulnerabilities found during the scan.

Even when setting `ignoreScanErrors: true`, the task still completes with a `SucceededWithIssues` status if any vulnerabilities are found, regardless of severity. This behavior limits pipeline flexibility, especially when users want to fail builds only for high or critical vulnerabilities but ignore informational or low-level ones.

💡 **Proposed enhancement:**
Introduce a new input parameter such as `failOnSeverityThreshold` that defines the minimum severity level required to fail the task. For example:

```yaml
failOnSeverityThreshold: 'HIGH' # Possible values: CRITICAL, HIGH, MEDIUM, LOW, UNKNOWN, NONE
```

**Expected behavior examples:**

* Only `LOW` or `MEDIUM` vulnerabilities found → task status = `Succeeded`
* Any `HIGH` or `CRITICAL` vulnerability found → task status = `Failed`

This would allow teams to enforce their own policies directly in CI/CD, instead of relying on secondary scripting or wrapping the task manually.

#### Agent details

* Type: Microsoft-Hosted Agent
* OS: Linux (ubuntu-latest)
* Version: 3.225.0

#### Task Version

* `trivy@2`
* Installed from: Azure DevOps Marketplace (official version)

#### Task Inputs

```yaml
- task: trivy@2
  inputs:
    version: 'latest'
    type: 'image'
    target: 'example.azurecr.io/app:latest'
    scanners: 'vuln'
    severities: 'CRITICAL,HIGH,MEDIUM,LOW'
    ignoreUnfixed: false
    ignoreScanErrors: true
    reports: 'html'
    publish: true
    debug: false
    # proposed parameter
    failOnSeverityThreshold: 'HIGH'
```

#### Error message

There is no actual error. However, the task always ends with:

```log
##[warning]Issues found.
Finishing: Trivy Scan (Image)
```

Even if only low severity vulnerabilities are present — which still causes the job to appear as `SucceededWithIssues`.

---
