### ISSUE TITLE
Terraform scan fails with error "Issues found".

### ISSUE THREAD

**Issue by michasacuer** [aquasecurity/trivy-azure-pipelines-task#188]
#### Describe the bug

Received:

```
##[error]Issues found.
```

After first run

#### Agent details

* Type: Microsoft-Hosted Agent
* OS: Windows

#### Task Version

V2
2.6.89
v0.63.0

#### Task Inputs

```yaml
- task: trivy@2
  inputs:
    version: 'latest'
    type: 'filesystem'
    scanners: 'license, misconfig, secret, vuln'
    failOnSeverityThreshold: 'HIGH'
    target: src/terraform
    options: '--debug --tf-vars src/tfvars/dev.tfvars'

```

#### Error message

![Image](https://github.com/user-attachments/assets/4bbf0c7f-eef1-4582-8991-103faa0eee39)

#### Debug output

https://gist.github.com/michasacuer/478cd592dcf9304e6533240f222d96f0
