### ISSUE TITLE
Unable to scan docker images using Azure pipeline

### ISSUE THREAD

**Issue by kkhamruddin-pk** [aquasecurity/trivy-azure-pipelines-task#19]
Unable to scan docker images using Azure pipeline

Below is the docker version that I am using
<img width="365" alt="image" src="https://user-images.githubusercontent.com/33874243/201078676-ba9e026e-a415-40ae-9c17-f71fd90174ac.png">

Below is the pipeline code
![image](https://user-images.githubusercontent.com/33874243/201079048-5760238a-ee12-4d8a-b4f7-b8ad55a484cc.png)

Below is the pipeline job
<img width="712" alt="image" src="https://user-images.githubusercontent.com/33874243/201079256-369fe7c5-69df-41f5-b1a6-f0cfc1e6c687.png">

Below is the trivy docker command it is running internally
/usr/bin/docker run --rm -v /root/.docker:/root/.docker -v /tmp:/tmp -v /azp/_work/1/s:/src --workdir /src aquasec/trivy:latest image --exit-code 1 --format json --output /tmp/trivy-results-0.8049780762459939.json --security-checks vuln,config,secret XXXXXXXX.azurecr.io/import:46517'

Can someone please help?

When I run  the above docker command manually I am getting the below
<img width="960" alt="image" src="https://user-images.githubusercontent.com/33874243/201079868-bef83539-042b-4a22-ba08-e2852b16aac2.png">

I tried changing the volume to "-v /var/run/docker.sock:/var/run/docker.sock" then it is working.

How to fix this using azure pipeline trivy task. Please suggest

**Comment by joaoacmota** [comment]
i have the same issue. While i wait for this to be fixed I use the docker image to export a junit report that I publish. This is the pipeline template I use for it

```
steps:
  - ${{ if parameters.image }}:
    - script: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /tmp:/tmp -v $(System.DefaultWorkingDirectory):/src  aquasec/trivy:latest  --exit-code ${{parameters.failOnScanErrors}} --format template --template "@contrib/junit.tpl" -o /src/${{ parameters.reportName }}.xml --security-checks vuln,config,secret image ${{ parameters.acrName }}/${{ parameters.image }}
  - ${{ else }}:
    - script: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v /tmp:/tmp -v $(System.DefaultWorkingDirectory):/src  aquasec/trivy:latest  --exit-code ${{parameters.failOnScanErrors}} --format template --template "@contrib/junit.tpl" -o /src/${{ parameters.reportName }}.xml --security-checks vuln,config,secret fs ${{ parameters.path }}
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: ${{ parameters.reportName }}.xml
```
