### ISSUE TITLE
[Feature request] Support for local images

### ISSUE THREAD

**Issue by ingentismg** [aquasecurity/trivy-azure-pipelines-task#23]
Hi,

we would like to scan local images as part of our build process, before we push them.
Currently the task has no option to enable mounting of the local docker socket to scan local images.

**Comment by ferronsw** [comment]
You can already do this:

Just set `docker` to false like:

```
    - task: trivy@1
      inputs:
        docker: false
        image: $(imageId)
```
