### ISSUE TITLE
Unable to process the results

### ISSUE THREAD

**Issue by lbouriez** [aquasecurity/trivy-azure-pipelines-task#24]
While running it on our pipeline, it's impossible to upload the file result:
![image](https://user-images.githubusercontent.com/4749766/206200903-85368bc1-3cbf-4060-bc34-68055011d806.png)

The code is:
```
- task: trivy@1
  displayName: "Trivy Scan"
  inputs:
    version: "${{ parameters.TrivyVersion }}"
    path: .
```
