### ISSUE TITLE
Version 1.4.0 breaking change when using TRIVY_SEVERITY environment variable

### ISSUE THREAD

**Issue by cjbush** [aquasecurity/trivy-azure-pipelines-task#32]
I'm not sure if this is an issue with the plugin itself, or with the underlying version of trivy that it's using, but as of 2 hours ago when the 1.4.0 release went out, my builds are all failing now. I was setting the TRIVY_SEVERITY environment variable in my task like so:

```yaml
  - task: trivy@1
    displayName: 'Fail build for critical vulnerabilities'
    inputs:
      version: 'latest'
      docker: false
      path: '$(System.DefaultWorkingDirectory)'
    env:
      TRIVY_SEVERITY: 'HIGH,CRITICAL'
      TRIVY_IGNOREFILE: '$(System.DefaultWorkingDirectory)/.trivyignore'
```

and it seems to be ignoring that and using the value passed in on the command line now (which defaults to 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'). Is there a way to get the old behavior back without going in and modifying all of my dozens of pipelines to pass in the values I want on the command line?
