### ISSUE TITLE
Request to change --security-checks to --Scanners

### ISSUE THREAD

**Issue by akhil-ph** [aquasecurity/trivy-azure-pipelines-task#41]
When I'm using trivy task in my pipeline, I'm getting a warning `--security-checks` is deprecated use `--scanners` instead.
I'm using trivy version `0.42.1`

please make this change in a way that we can choose the type of scanner to use via argument
eg:
```yml
- task: trivy@1
  displayName: 'trivy container'
  inputs:
    version: 'v0.42.1'
    docker: false
    image: 'node:latest'
    scanners: 'vuln,secret'
    severities: 'HIGH,CRITICAL'
    exitCode: '1'
    ignoreUnfixed: true
    options: '--vuln-type library'
```

**Comment by srmds** [comment]
We are also encountering the deprecation warning.

Build output for trivy task:

`2023-06-27T09:52:30.316Z	WARN	'--security-checks' is deprecated. Use '--scanners' instead.`

**Comment by srmds** [comment]
By leveraging trivy.yaml [config file](https://aquasecurity.github.io/trivy/v0.42/docs/references/configuration/config-file/), setting _scanners_ instead of _[security-checks](https://github.com/aquasecurity/trivy/blob/v0.33.0/examples/trivy-conf/trivy.yaml)_ the deprecation warning goes away:

`trivy ... --config trivy.yaml `

trivy.yaml:

```yaml
...

scan:
  ...
  scanners: 
    - config
    - vuln
    - secret 
```
