### ISSUE TITLE
Trivy@1 failing with unknown flag: --scanner

### ISSUE THREAD

**Issue by olivebay** [aquasecurity/trivy-azure-pipelines-task#69]
Reporting the following issue. When running the below task from ADO

```
- task: trivy@1
  inputs:
    version: 'latest'
    docker: false
    path: './'
    exitCode: '0'
    devMode: true
```

Fails with the following 
```
Preparing output location...
Run requested using local Trivy binary...
Finding correct Trivy version to install...
Required Trivy version is v0.53.0
Downloading Trivy...
Downloading: https://github.com/aquasecurity/trivy/releases/download/v0.53.0/trivy_0.53.0_Linux-64bit.tar.gz
Extracting Trivy...
[..]

FATAL	Fatal error	unknown flag: --scanner
Scan local filesystem
```
