### ISSUE TITLE
publish results from other results / sources

### ISSUE THREAD

**Issue by BuriKizilkaya** [aquasecurity/trivy-azure-pipelines-task#76]
Is it possible to publish the results of the trivy scan, when the SBOM + Vulnerability Scan was built from a custom script task? 

for example: 

```yml

- script: |
     docker run trivy ... -o /results.json

- task: trivy@1
   inputs:
     result_path: /results.json

```
