### ISSUE TITLE
Provide the ability to process scan results independently

### ISSUE THREAD

**Issue by a-poluyanov** [aquasecurity/trivy-azure-pipelines-task#79]
Hello again! I have different pre-production pipelines, which have many services, my task is to scan all images for all vulnerabilities, of any level, but also to make the pipeline crash with an error if critical ones are found.

My approximate test pipeline looks like this, here I first just output the scan results, and then search for a critical vulnerability. But during the output in the UI it looks ugly. Two results are displayed, one empty (since no critical vulnerabilities were found) and one with everything as I need
```YAML

- task: AquaSecurityOfficial.trivy-official.custom-build-release-task.trivy@1
    displayName: 'Scan all vulnerabilitie1s'
    inputs:
      version: $(TrivyVersion)
      docker: $(InDocker)
      image: 'docker-registry.my-company.io/projects/test/superset-superset:2.1.0-test'
      ignoreUnfixed: true
      exitCode: 0
      options: '--scanners vuln --cache-dir /tmp/trivy-cache --report all'
  - ${{ if eq(parameters.ForceImagePushImageWithVulnerability, false) }}:
    - task: AquaSecurityOfficial.trivy-official.custom-build-release-task.trivy@1
      displayName: 'Find CRITICAL'
      inputs:
        version: $(TrivyVersion)
        docker: $(InDocker)
        image: 'docker-registry.my-company.io/projects/test/superset-superset:2.1.0-test'
        options: '--scanners vuln --severity CRITICAL --cache-dir /tmp/trivy-cache --report all'
```

I have two solutions to a similar problem, which I also saw on the Internet, but no one dared to solve it

1. Add the ability to display all vulnerabilities, but give a negative exit code only if we need them. I understand that this probably needs to be created as an Issue in your main repository. If so, let me know.
```bash
--scanners vuln --cache-dir /tmp/trivy-cache --report all --exit-code 1 --exit-code-severity CRITICAL
```

That is, here I propose to add another option  `--exit-code-severity`  in which there will be an exit code, in this case all vulnerabilities will be included in the result, and we will be able to set the severity at which our pipeline can fall

2. The second option, I think, is needed not only for this case but also for others. I can't pass the following option to the parameters during the launch of this task
`--output result.json`

That is, I can't set the file name for output, I don't want it to be called that, and I want to keep the file name in a variable so that I can process it with my script using bash and jq, which will allow me to output all the vulnerabilities and then with my scripts how I want to process this file. I suggest adding the `outputFileName` option

This will give us the ability to create our own names for the output file, which will make the task more flexible.
