### ISSUE TITLE
##[error]The current operating system is not capable of running this  trivy task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.

### ISSUE THREAD

**Issue by Ketone16** [aquasecurity/trivy-azure-pipelines-task#99]
I am facing this issue in azure devops pipeline from the past 2 days, in trivy task ,  we have installed the trivy extension but it auto-updated to 1.6.1 on 14 Feb 2025 , causing to fail  the pipeline .

- and I am using the **ubuntu 22.04 agent from the past 2 years** 
and I guess I cannot downgrade it to 1.5.1 where it run fine, in  Azure DevOps > Organization Settings > Extensions.

- is this Trivy Azure DevOps extension (trivy@1) was recently updated to version 1.6.0 or 1.6.1, and this update might have **inadvertently made it Windows-only** or changed the way it detects the OS.

- please fix this asap.

-has anyone facing this ??

@owenrumney

**Comment by owenrumney** [comment]
Hey @Ketone16  - can you give me a bit more detail on the configuration?

I've just run the following job with no issues on `1.6.1` so would be good to know if you're doing a docker scan, image scan, which trivy version you're using?

```
trigger: none


pool:
  vmImage: ubuntu-latest

variables:
  SYSTEM_DEBUG: true

jobs:

- job: scan_local_project
  steps:
    - task: trivy@1
      inputs:
        docker: false
        version: 'latest'
        exitCode: '0'
        path: '.'
        cosignOutput: true
        sarifOutput: true

- job: previous version 
  steps:
    - task: trivy@1
      inputs:
        docker: false
        version: 'v1.59.0'
        exitCode: '0'
        path: '.'
        cosignOutput: true
        sarifOutput: true
```

For completeness I also ran it with the `ubuntu-22.04` image with no issues.


```
pool: 
  vmImage: ubuntu-22.04
```
